#https://gemmi.readthedocs.io/en/latest/hkl.html#mtz-format


import sys
import matplotlib.pyplot as plt
import gemmi
import matplotlib
matplotlib.use('Agg')

from pathlib import Path

DATADIR = str(Path(__file__).resolve().parent.parent.parent )+ "/"

for path in [DATADIR + "mtzdata/1ejg_phases.mtz"]:    
    mtz = gemmi.read_mtz_file(path)
    print(mtz.title)    
    for i in range(len(mtz.columns)):
        print(mtz.columns[i])
    intensity = mtz.column_with_label('FP')
    sigma = mtz.column_with_label('SIGFP')
    if intensity is None or sigma is None:
        sys.exit("Columns I and SIGI not in the file: " + path)
    x = mtz.make_1_d2_array()
    y = intensity.array / sigma.array
    plt.figure(figsize=(5,5))
    plt.hexbin(x, y, gridsize=180, bins='log', cmap='gnuplot2')
    plt.savefig("tst.png")


import numpy
# toxd_aupatt.map is generated by $CCP4/examples/unix/runnable/patterson
plt.close()
ccp4 = gemmi.read_ccp4_map(DATADIR + 'pdbdata/7uly.ccp4', setup=True)
arr = numpy.array(ccp4.grid, copy=False)
x = numpy.linspace(0, ccp4.grid.unit_cell.a, num=arr.shape[0], endpoint=False)
y = numpy.linspace(0, ccp4.grid.unit_cell.b, num=arr.shape[1], endpoint=False)
X, Y = numpy.meshgrid(x, y, indexing='ij')
plt.contour(X, Y, arr[:,:,100])
plt.gca().set_aspect('equal', adjustable='box')
plt.savefig("tst2.png")